# Generated by Django 6.0.6 on 2026-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_token', models.CharField(max_length=36, unique=True)),
                ('profile_thumb', models.ImageField(blank=True, null=True, upload_to='students/temp/thumb/')),
                ('profile_medium', models.ImageField(blank=True, null=True, upload_to='students/temp/medium/')),
                ('profile_large', models.ImageField(blank=True, null=True, upload_to='students/temp/large/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='profile_large',
            field=models.ImageField(blank=True, null=True, upload_to='students/large/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_medium',
            field=models.ImageField(blank=True, null=True, upload_to='students/medium/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='students/thumb/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
